version: "3.7"

services:
  app:
    image: mattermost/mattermost-prod-app:${VERSION:-5.23.1}
    volumes:
      - ${VOLUME_PATH}data:/mattermost/data
      - ${VOLUME_PATH}config:/mattermost/config
      - ${VOLUME_PATH}plugins:/mattermost/plugins
    environment:
      - MM_USERNAME=mattermost
      - MM_PASSWORD=myp@ssw0rd
      - MM_DBNAME=mattermost
      - MM_SERVICESETTINGS_SITEURL=${SCHEME:-http}://${DOMAIN:-mattermost.localhost}
      - MM_LOCALIZATIONSETTINGS_DEFAULTCLIENTLOCALE=${LOCALE:-fr}
      - MM_LOCALIZATIONSETTINGS_AVAILABLELOCALES=${LOCALE:-fr}
      - MM_EMAILSETTINGS_ENABLEPREVIEWMODEBANNER=FALSE
      - MM_EMAILSETTINGS_SMTPUSERNAME=${SMTP_USERNAME}
      - MM_EMAILSETTINGS_SMTPPASSWORD=${SMTP_PASSWORD}
      - MM_EMAILSETTINGS_SMTPSERVER=${SMTP_SERVER}
      - MM_EMAILSETTINGS_SMTPPORT=${SMTP_PORT}
      - MM_PLUGINSETTINGS_ENABLEUPLOADS=${ENABLE_PLUGINS:-true}
      - MM_TEAMSETTINGS_MAXUSERSPERTEAM=${MAXUSERSPERTEAM:-100}
    networks:
      - internal

  web:
    image: mattermost/mattermost-prod-web:${VERSION-5.23.1}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.mattermost-${NUMBER:-1}.rule=Host(`${DOMAIN:-mattermost.localhost}`)
        - traefik.http.routers.mattermost-${NUMBER:-1}.entrypoints=${SCHEME:-http}
        - traefik.http.routers.mattermost-${NUMBER:-1}.service=mattermost-${NUMBER:-1}
        - traefik.http.routers.mattermost-${NUMBER:-1}.middlewares=mattermost-${NUMBER:-1}
        - traefik.http.services.mattermost-${NUMBER:-1}.loadbalancer.server.port=80
        - traefik.http.middlewares.mattermost-${NUMBER:-1}.headers.customRequestHeaders.X-Forwarded-Port=443
        - traefik.http.middlewares.mattermost-${NUMBER:-1}.headers.customRequestHeaders.X-Forwarded-Proto=${SCHEME:-http}
    networks:
      - internal
      - traefik

  db:
    image: postgres:9.6-alpine
    volumes:
      - ${VOLUME_PATH}db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mattermost
      - POSTGRES_PASSWORD=myp@ssw0rd
      - POSTGRES_DB=mattermost
    networks:
      - internal

volumes:
  data:
  config:
  plugins:
  db:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
