# DOMAIN=example.com CROWDSEC_BOUNCER_API_KEY=key COLLECTIONS=crowdsecurity/traefik docker stack deploy -c crowdsec.yml crowdsec

version: '3.8'

services:
  crowdsec:
    image: crowdsecurity/crowdsec:${VERSION:-latest}
    environment:
      - GID=${GID-1000}
      - COLLECTIONS=${COLLECTIONS:-crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/whitelist-good-actors crowdsecurity/iptables crowdsecurity/linux crowdsecurity/sshd}
      - CUSTOM_HOSTNAME=${CUSTOM_HOSTNAME:-crowdsec}
    command: ["/bin/bash", "-c", "cscli hub update && cscli parsers install crowdsecurity/traefik-logs && cscli parsers install crowdsecurity/http-logs && cscli machines add --password 'test' && crowdsec -c /etc/crowdsec/config.yaml"]
    volumes:
      - ${VOLUME_PATH}config:/etc/crowdsec
      - ${VOLUME_PATH}data:/var/lib/crowdsec/data/
      - /var/log/traefik:/var/log/traefik:ro
    networks:
      - traefik
      - internal

  crowdsec-bouncer:
    image: fbonalair/traefik-crowdsec-bouncer:latest
    environment:
      - PORT=8083
      - CROWDSEC_BOUNCER_API_KEY=${CROWDSEC_BOUNCER_API_KEY:-nQfJinrUuzNNRDZ1jSD3aUi/rU6fv6n02BXLZMLQzVs}
      - CROWDSEC_AGENT_HOST=crowdsec:8080
    networks:
      - traefik
      - internal

volumes:
  data:
  config:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
