# docker stack deploy -c traefik.yml traefik

version: '3.8'

services:
  traefik:
    image: traefik:${VERSION:-v2.11.3}
    command:
      # - --log.level=DEBUG
      - --accesslog=true
      - --accesslog.filepath=/var/log/traefik/access.log
      - --providers.docker
      - --providers.docker.network=traefik-net
      - --providers.docker.exposedByDefault=false
      - --providers.docker.swarmMode=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --entrypoints.traefik.address=:8081 # Move dashboard to port 8081
      - --entrypoints.https.http.middlewares=crowdsec-bouncer@docker
      - --entrypoints.https.proxyProtocol.trustedIPs=${TRUSTED_IPS:-127.0.0.1}
      - --entrypoints.https.forwardedHeaders.trustedIPs=${TRUSTED_IPS:-127.0.0.1}
      - --entrypoints.https.address=:443
      - --entrypoints.http.address=:80
      - --entrypoints.http.proxyProtocol.trustedIPs=${TRUSTED_IPS:-127.0.0.1}
      - --entrypoints.http.forwardedHeaders.trustedIPs=${TRUSTED_IPS:-127.0.0.1}
      - --entrypoints.http.http.redirections.entryPoint.to=https
      - --entrypoints.http.http.redirections.entryPoint.scheme=https
      - --entrypoints.http.http.redirections.entrypoint.permanent=true
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL:-admin@example.com}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --api.dashboard=${API_DASHBOARD:-false} # Enable Dashboard
      - --api.insecure=false
      - --api.debug=true
    volumes:
      - ${VOLUME_PATH}logs:/var/log/traefik/
      - ${VOLUME_PATH}letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

    ports:
      - {target: 80, published: 80, mode: host, protocol: tcp}
      - {target: 443, published: 443, mode: host, protocol: tcp}
      - {target: 8081, published: 8081, mode: host, protocol: tcp} # For Traefik dashboard access

    deploy:
      mode: ${MODE:-replicated}
      labels:
        - traefik.enable=true
        - traefik.http.routers.traefik.entrypoints=https
        - traefik.http.routers.traefik.middlewares=crowdsec-bouncer
        - traefik.http.services.traefik.loadbalancer.server.port=8080
        - traefik.http.middlewares.crowdsec-bouncer.forwardauth.address=http://crowdsec-bouncer:8080/api/v1/forwardAuth
        - traefik.http.middlewares.crowdsec-bouncer.forwardauth.trustForwardHeader=true

        # New labels for Traefik dashboard and API access with basic auth
        - traefik.http.routers.dashboard.rule=Host(`${DOMAIN:-traefik.localhost}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
        - traefik.http.routers.dashboard.entrypoints=traefik
        - traefik.http.routers.dashboard.service=api@internal
        - traefik.http.routers.dashboard.middlewares=auth@docker
        
        # Basic Authentication for Traefik Dashboard | htpasswd -nbB admin password
        - traefik.http.middlewares.auth.basicauth.users=traefik-admin:$2y$05$ygqIFYgORdwvOMUkTzAJL.jwUu1DQcZKz92k0HA7ucJWxKZe6vBvy

volumes:
  letsencrypt:
  logs:

networks:
  default:
    external: true
    name: traefik-net
