# docker stack deploy -c traefik.yml traefik

version: '3.8'

services:
  traefik:
    image: traefik:${VERSION:-v2}
    command:
      - --log.level=DEBUG
      - --providers.docker
      - --providers.docker.network=traefik-net
      - --providers.docker.exposedByDefault=false
      - --providers.docker.swarmMode=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --entrypoints.https.proxyProtocol.trustedIPs=${TRUSTED_IPS:-127.0.0.1/8,10.0.0.0/8}
      - --entrypoints.https.forwardedHeaders.trustedIPs=${TRUSTED_IPS:-127.0.0.1/8,10.0.0.0/8}
      - --entrypoints.https.address=:443
      - --entrypoints.http.address=:80
      - --entrypoints.http.proxyProtocol.trustedIPs=${TRUSTED_IPS:-127.0.0.1/8,10.0.0.0/8}
      - --entrypoints.http.forwardedHeaders.trustedIPs=${TRUSTED_IPS:-127.0.0.1/8,10.0.0.0/8}
      - --entrypoints.http.http.redirections.entryPoint.to=https
      - --entrypoints.http.http.redirections.entryPoint.scheme=https
      - --entrypoints.http.http.redirections.entrypoint.permanent=true
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL:-admin@example.com}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --api.dashboard=${API_DASHBOARD:-true} # Enable Dashboard
      - --api.insecure=false
      - --api.debug=true
      # DEV - use this for testing purposes or else you might get blocked - # CHANGE THIS
      - --certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
    volumes:
      - ${VOLUME_PATH}letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - {target: 80, published: 80, mode: host, protocol: tcp}
      - {target: 443, published: 443, mode: host, protocol: tcp}
    deploy:
      mode: ${MODE:-global}
      placement:
        constraints:
          - node.role==manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.traefik.entrypoints=https
        - traefik.http.routers.traefik.rule=Host(`${DOMAIN:-traefik.localhost}`)
        - traefik.http.routers.traefik.service=api@internal
        - traefik.http.services.traefik.loadbalancer.server.port=8080 # Fix missing port here

volumes:
  letsencrypt:

networks:
  default:
    external: true
    name: traefik-net